cppcon21:
  - '.github/path-filters.yml'
  - '.github/workflows/pages.yml'
  - 'slides/cppcon21/**'

cppcon23:
  - '.github/path-filters.yml'
  - '.github/workflows/pages.yml'
  - 'slides/cppcon23/**'
