name: talks

on: push

jobs:
  check-markdown-links:
    name: check-markdown-links
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".markdown.json"
