name: talks

on: push

jobs:
  check-markdown-links:
    name: check-markdown-links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.markdown.json'
